export default function App() {
  return (
    <div>
      <h1>Adam Podkowinski</h1>
      <button type="button">Click me</button>
      <p>Color palette generated by ChatGPT</p>
      <div className="bar">
        <ul>
          <li>siema</li>
          <li>elo</li>
          <li>morelo</li>
        </ul>
      </div>
    </div>
  );
}
